In [1]:
import pandas as pd
import openai
import json
import backoff
from tqdm import tqdm
import numpy as np
import os

## Load Procedures and Teaching Tasks

In [2]:
procedures_df = pd.read_excel('/home/firdavs/surgery/annotations/Overview of Cases.xlsx')
procedures_df = procedures_df.rename(columns={'LFB Case #': 'case_id', 'Procedure': 'procedure'})
procedures_df = procedures_df[['case_id', 'procedure']]
procedures_df.head()

   case_id              procedure
0        1  radical prostatectomy
1        2   simple prostatectomy
2        3  radical prostatectomy
3        4  radical prostatectomy
4        5  radical prostatectomy

In [5]:
teaching_steps_df = pd.read_csv('/home/firdavs/surgery/annotations/console_times/combined_console_times_secs.csv')
teaching_steps_df.reset_index(drop=True, inplace=True)
teaching_steps_df = teaching_steps_df.rename(columns={'Teaching Step': 'teaching_step', 'On time (secs)': 'start_secs', 'Off time (secs)': 'end_secs'})
teaching_steps_df = teaching_steps_df[['case_id', 'teaching_step', 'start_secs', 'end_secs']]
teaching_steps_df.head()

   case_id          teaching_step  start_secs  end_secs
0        1  Lymph node dissection         -28      1802
1        1      Dropping bladder         1802      2042
2        1      Endopelvic fascia        2042      2132
3        1           Bladder neck        2132      2762
4        1           Bladder neck        2762      2912

In [11]:
procedures_df['procedure'].unique()

array(['radical prostatectomy', 'simple prostatectomy', 'nephrectomy',
       'nephroureterectomy', 'partial nephrectomy',
       'inguinal hernia repair', 'cystectomy and ilial conduit '],
      dtype=object)

In [24]:
teaching_steps_df['teaching_step'].unique()

array(['Lymph node dissection', 'Dropping bladder ', 'Endopelvic fascia',
       'Bladder neck', 'SV', 'posterior plane', 'Posterior plane',
       'Bladder neck recon', 'Pedicle/NVB', 'apical dissection', 'DVC',
       'oblique checks', 'hemostasis, rocco stitch', 'VUA',
       'Adenoma dissection', 'Dropping bladder', nan, 'Bladder Neck',
       'Pedicles/NVB/apical dissection', 'Hemostasis', 'Rocco stitch',
       'dropping bladder', 'Pedicles/NVB', 'Apical dissection',
       'DVC, hemostasis', 'Rocco', 'Pexy',
       'Bowel mobilization + Lymph dissection', 'Endopelvic fascia ',
       'Bladder neck / SV', 'pedicles / NVB', 'apical dissection ',
       'Hemostasis, DVC', 'pexy', 'extra node dissection',
       'Bowel mobilization', 'dissection', 'dissecting ',
       'stapling ureter ', 'Bagging specimen ',
       'undocking, specimen out, closing incisions', 'docking robot',
       '(setting up, waiting for attending)', ' Cystotomy',
       'Stay Sutures', 'Adenoma Dissection', 'Bladder Neck ',
       'Closing Bladder', 'Bowel Mobilization', 'Dissection',
       'bowel mobilization', 'Dissection+VUA', 'Cystotomy',
       'hemostasis/bladder neck', 'Hemostasis+Trigonization',
       'Lateral pedicle recon', 'Closing bladder',
       'Lymph Node Dissection', 'NVB', 'DVC, hemostasis, Rocco stitch',
       'lymph node dissection ', 'lymph node dissection',
       'dropping bladder ', 'DVC, hemostasis, Rocco', 'hemostasis ',
       'Cystotomy (Stay sutures)', 'Adenoma dissection ',
       'Bladder neck (hemostasis)', 'Bladder neck (trigonization?)',
       'closing bladder', 'Bowel Mobilization (partial nephrectomy)',
       'Ultrasound/tumor identification', 'Cross clamping',
       'Tumor dissection', 'suturing kidney', 'stay sutures ',
       'Peritoneal Flap and Mesh Pocket Dissection', 'anchoring of mesh',
       'closing peritoenum ',
       'Bowel mobilization cystectomy, stay sutures ', 'cystotomy ',
       'Stay sutures, rescue stitch', 'adenoma dissection',
       'bladder closure', 'endopelvic fascia', 'bladder neck', 'SVs',
       'pedicles /NVB', 'oblique check', 'bagging', 'hemostasis',
       'rocco stitch', 'Lymph node dissection ', 'bladder neck ',
       'SV/Vas', 'Lateral pedicle', 'Bowel Mobilization- Nephrectomy',
       'cystotomy - simple prostatectomy', 'cystotomy',
       'bladder neck (suture)', 'closing bladder ', 'Urethropexy',
       'Vesicopexy', 'dropping bladder (+fixing hole in bladder)',
       'bagging specimen, bubble test', 'stent', 'defatting prostate',
       'pedicles/NVB', 'bagging specimen, dre, irrigation',
       'hemostasis (suture)', 'leak testing, etc', 'posterior plane ',
       'DVC stitch', 'Pexy + hemostasis', 'Lysis of adhesions',
       'suturing - bladder holes',
       'bagging specimen, irrigation, hemostasis', 'VUA, pexy'],
      dtype=object)

## Generate Definitions

In [13]:
# Get OpenAI API key
with open('../keys.json', 'r') as f:
    keys = json.load(f)
openai_api_key = keys['openai_api_key-personal']

In [14]:
#@title Function for Initializing OpenAI and Prompting
def initOpenAI(key):
    client = openai.OpenAI(
    # This is the default and can be omitted
    api_key=key,
    )
    return client

# Function to List Available Models
def listModels(client):
    models = client.models.list()
    model_names = [model.id for model in models.data]
    return model_names

In [25]:
def get_prompt_procedure(procedure):
    instruction = f"You are working in the domain of urology surgery. You are tasked with defining surgical procedures in 3-4 sentences."
    label_prompt = f"Define the surgical procedure: {procedure}"

    return instruction, label_prompt

def get_prompt_teaching_step(teaching_step):
    instruction = f"You are working in the domain of urology surgery. You are tasked with defining surgical teaching steps in 1-2 sentences."
    label_prompt = f"Define the teaching step: {teaching_step}"

    return instruction, label_prompt
    
def labelGPT(client, model_name, instruction, label_prompt, temperature=0.0):
    @backoff.on_exception(backoff.expo, (openai.RateLimitError,
                                        openai.APIError,
                                        ConnectionResetError,
                                        json.decoder.JSONDecodeError))

    def completions_with_backoff(**kwargs):
        return client.chat.completions.create(**kwargs)

    # Prompt OpenAI
    # https://github.com/openai/openai-python
    response = completions_with_backoff(model=model_name,
                                        temperature=temperature,
                                        messages=[{"role": "system", "content": instruction},
                                                {"role":"user", "content": label_prompt}])

    gen = response.choices[0].message.content
    return gen

In [16]:
openai_client = initOpenAI(openai_api_key)
available_models = listModels(openai_client)
model_name = 'gpt-4o-mini'

In [17]:
procedure_mappings = {}
unique_procedures = procedures_df['procedure'].unique().tolist()
for i in tqdm(range(len(unique_procedures)), desc='Procedures'):
    procedure = unique_procedures[i]
    instruction, label_prompt = get_prompt_procedure(procedure)
    gen = labelGPT(openai_client, model_name, instruction, label_prompt)
    procedure_mappings[procedure] = gen

Procedures: 100%|██████████| 7/7 [00:23<00:00,  3.30s/it]

In [18]:
print(json.dumps(procedure_mappings, indent=4))

{
    "radical prostatectomy": "Radical prostatectomy is a surgical procedure that involves the complete removal of the prostate gland along with some surrounding tissue, including the seminal vesicles and sometimes nearby lymph nodes. This procedure is primarily performed to treat localized prostate cancer and aims to eliminate cancerous cells while preserving as much surrounding healthy tissue as possible. It can be done through open surgery or minimally invasive techniques, such as laparoscopic or robotic-assisted surgery. Postoperative recovery may involve managing urinary incontinence and erectile dysfunction, which are common side effects.",
    "simple prostatectomy": "A simple prostatectomy is a surgical procedure aimed at removing the prostate gland and some surrounding tissue to alleviate symptoms caused by benign prostatic hyperplasia (BPH) or prostate cancer. This procedure is typically performed through an incision in the lower abdomen or via a transurethral approach, depending on the patient's condition and the surgeon's preference. The goal is to relieve urinary obstruction and improve urinary flow while minimizing complications. Recovery time varies, but patients often experience significant improvement in urinary symptoms post-surgery.",
    "nephrectomy": "Nephrectomy is a surgical procedure that involves the removal of a kidney. It can be performed as a partial nephrectomy, where only a portion of the kidney is excised, or as a radical nephrectomy, which entails the complete removal of the kidney along with surrounding tissues, including the adrenal gland and nearby lymph nodes. This procedure is typically indicated for conditions such as kidney cancer, severe kidney damage, or donor kidney retrieval. Nephrectomy can be performed using open surgery or minimally invasive techniques, such as laparoscopic surgery, depending on the patient's condition and the surgeon's expertise.",
    "nephroureterectomy": "Nephroureterectomy is a surgical procedure that involves the removal of a kidney (nephrectomy) along with the entire ureter, which is the tube that carries urine from the kidney to the bladder. This procedure is typically performed to treat conditions such as kidney cancer, ureteral cancer, or severe urinary tract infections that do not respond to other treatments. The surgery can be done through an open approach or laparoscopically, depending on the patient's condition and the surgeon's expertise. Postoperative care is essential to monitor for complications and ensure proper recovery.",
    "partial nephrectomy": "Partial nephrectomy is a surgical procedure that involves the removal of a portion of a kidney while preserving the remaining healthy tissue. This technique is typically employed to treat localized kidney tumors or lesions, allowing for the excision of cancerous or diseased tissue while maintaining kidney function. The procedure can be performed using open surgery or minimally invasive techniques, such as laparoscopic or robotic-assisted surgery. Postoperative care focuses on monitoring kidney function and managing any potential complications.",
    "inguinal hernia repair": "Inguinal hernia repair is a surgical procedure aimed at correcting an inguinal hernia, which occurs when tissue, often part of the intestine, protrudes through a weak spot in the abdominal muscles in the groin area. The surgery can be performed using an open technique or laparoscopically, where small incisions are made, and a camera is used to guide the repair. The surgeon repositions the protruding tissue back into the abdomen and reinforces the abdominal wall, typically using mesh to provide additional support and reduce the risk of recurrence. Postoperative care includes monitoring for complications and managing pain, with most patients able to return to normal activities within a few weeks.",
    "cystectomy and ilial conduit ": "Cystectomy is a surgical procedure that involves the removal of the bladder, typically due to conditions such as bladder cancer, severe bladder dysfunction, or other significant bladder diseases. Following cystectomy, an ileal conduit is often created to divert urine from the kidneys to an external pouch. This involves taking a segment of the ileum (part of the small intestine) and fashioning it into a conduit that connects the ureters (the tubes carrying urine from the kidneys) to an opening in the abdominal wall, where urine is collected in an external ostomy bag. This procedure allows for the management of urinary output after bladder removal while maintaining kidney function."
}

In [35]:
procedures_df['procedure_defn'] = procedures_df['procedure'].map(procedure_mappings)
procedures_df.to_parquet('/home/firdavs/surgery/surgical_fb_generation/SurgicalFeedbackGeneration/data/urology-related/procedures.parquet', index=False)

In [27]:
teaching_step_mapppings = {}
unique_teaching_steps = teaching_steps_df['teaching_step'].unique().tolist()
for i in tqdm(range(len(unique_teaching_steps)), desc='Teaching Steps'):
    teaching_step = unique_teaching_steps[i]
    instruction, label_prompt = get_prompt_teaching_step(teaching_step)
    gen = labelGPT(openai_client, model_name, instruction, label_prompt)
    teaching_step_mapppings[teaching_step] = gen

Teaching Steps: 100%|██████████| 118/118 [02:52<00:00,  1.46s/it]

In [28]:
print(json.dumps(teaching_step_mapppings, indent=4))

{
    "Lymph node dissection": "Lymph node dissection involves the surgical removal of lymph nodes to assess for cancer spread, typically performed in conjunction with other procedures such as radical prostatectomy or cystectomy. The teaching step includes identifying the anatomical landmarks, ensuring proper technique to minimize complications, and understanding the implications of lymphatic drainage in urological malignancies.",
    "Dropping bladder ": "Dropping the bladder involves carefully mobilizing the bladder from its anatomical attachments to the pelvic structures, ensuring minimal trauma to surrounding tissues, and providing clear visualization of the surgical field for subsequent procedures. This step is crucial for accessing the prostate or other pelvic organs while maintaining hemostasis and preserving bladder function.",
    "Endopelvic fascia": "The endopelvic fascia is a connective tissue layer that supports pelvic organs and is crucial in urological surgeries. During teaching, emphasize its anatomical significance, the importance of preserving it to maintain pelvic support, and techniques for identifying and dissecting it safely to avoid complications.",
    "Bladder neck": "The bladder neck is the region where the bladder connects to the urethra, and during surgical teaching, it is crucial to demonstrate the anatomy and function of this area, emphasizing its role in urinary continence and the potential complications that can arise from surgical manipulation, such as in prostatectomy procedures. Instruct trainees on identifying the bladder neck's landmarks and techniques for preserving its integrity during surgery to minimize postoperative complications.",
    "SV": "In urology surgery, the teaching step \"SV\" refers to \"Surgical Visualization,\" which emphasizes the importance of clear and effective visualization of the surgical field through proper positioning, retraction, and use of appropriate lighting and magnification techniques to enhance the surgeon's ability to identify anatomical structures and perform precise interventions.",
    "posterior plane": "The posterior plane refers to the surgical approach where the incision is made along the posterior aspect of the anatomical structure, allowing access to the underlying tissues and organs. In urology, this step often involves careful dissection to avoid damaging surrounding structures while providing a clear pathway to the target area, such as the prostate or bladder.",
    "Posterior plane": "The posterior plane refers to the anatomical space located behind the bladder and prostate, which is critical for accessing the pelvic structures during urological surgeries. In teaching this step, emphasize the importance of identifying and carefully dissecting the posterior plane to avoid injury to surrounding nerves and vessels while facilitating access to the surgical site.",
    "Bladder neck recon": "Bladder neck reconstruction involves the surgical technique of repairing or reconstructing the bladder neck to restore normal function, often following injury or disease. The teaching step includes careful dissection of surrounding tissues, identification of the bladder neck anatomy, and precise suturing techniques to ensure proper alignment and tension for optimal healing and urinary control.",
    "Pedicle/NVB": "The Pedicle/Nerve Vascular Bundle (NVB) step involves careful identification and preservation of the neurovascular structures during urological surgery, particularly in procedures like prostatectomy, to minimize the risk of nerve damage and maintain erectile function. Surgeons should be trained to meticulously dissect around these structures, using appropriate techniques to ensure their integrity while achieving the surgical goals.",
    "apical dissection": "Apical dissection involves carefully separating the tissue at the apex of the prostate to access the surrounding structures while preserving critical neurovascular bundles. This step is crucial for minimizing complications and ensuring adequate oncological control during prostatectomy procedures.",
    "DVC": "DVC, or \"Dorsal Venous Complex,\" refers to the anatomical structure that is critical in urological surgeries, particularly during penile procedures. Teaching this step involves instructing trainees on the identification and management of the DVC to prevent excessive bleeding and ensure proper surgical technique during operations such as circumcision or penile reconstruction.",
    "oblique checks": "Oblique checks involve assessing the orientation and positioning of the surgical instruments and anatomical structures during a urological procedure to ensure proper alignment and access. This step is crucial for minimizing complications and optimizing the surgical approach.",
    "hemostasis, rocco stitch": "Hemostasis involves the meticulous control of bleeding during surgery, ensuring that all blood vessels are adequately clamped, cauterized, or ligated to prevent excessive blood loss. The Rocco stitch is a specific surgical technique used to secure the bladder neck to the pelvic floor, promoting hemostasis and providing support to prevent postoperative complications such as urinary incontinence.",
    "VUA": "Vesicourethral anastomosis (VUA) is the surgical step where the bladder is reconnected to the urethra after prostatectomy or bladder surgery, ensuring proper alignment and tension-free suturing to facilitate optimal healing and urinary function. This step typically involves careful dissection, identification of anatomical landmarks, and the use of absorbable sutures to secure the anastomosis.",
    "Adenoma dissection": "Adenoma dissection involves carefully identifying and separating the adenomatous tissue from surrounding structures using precise surgical techniques, ensuring minimal trauma to adjacent healthy tissue. This step is crucial for achieving complete resection while preserving functional anatomy and reducing the risk of complications.",
    "Dropping bladder": "Dropping the bladder involves carefully mobilizing the bladder from its anatomical attachments to the pelvic structures, ensuring that the surrounding tissues are preserved while providing adequate exposure for the surgical procedure. This step is crucial for accessing the underlying structures and minimizing the risk of injury during surgery.",
    "NaN": "It seems like \"nan\" may be a typographical error or an incomplete term. If you meant to refer to a specific surgical teaching step or concept in urology surgery, please provide more context or clarify the term, and I would be happy to assist you!",
    "Bladder Neck": "The bladder neck is the region where the bladder connects to the urethra, and during surgical teaching, it is crucial to demonstrate the anatomy and function of the bladder neck, emphasizing its role in urinary continence and the techniques for preserving its integrity during procedures such as prostatectomy or bladder surgery. Instructors should guide trainees through identifying the bladder neck's landmarks, understanding its relationship with surrounding structures, and practicing surgical maneuvers that minimize trauma to this area.",
    "Pedicles/NVB/apical dissection": "During the pedicles, neurovascular bundles (NVB), and apical dissection step, the surgeon carefully identifies and preserves the neurovascular structures while mobilizing the prostate and surrounding tissues. This involves meticulous dissection to minimize damage to the nerves and blood vessels, ensuring optimal functional outcomes post-surgery.",
    "Hemostasis": "Hemostasis in urology surgery involves the meticulous control of bleeding during the procedure, utilizing techniques such as cauterization, ligation, or the application of hemostatic agents to ensure a bloodless surgical field and minimize postoperative complications. It is crucial to assess and secure all vascular structures before proceeding to the next steps of the surgery.",
    "Rocco stitch": "The Rocco stitch is a surgical technique used during radical prostatectomy to provide support to the bladder neck and maintain continence postoperatively. It involves suturing the bladder neck to the pelvic floor, which helps to preserve the anatomy and function of the surrounding structures.",
    "dropping bladder": "Dropping the bladder involves carefully mobilizing the bladder from its anatomical attachments to the pelvic structures, ensuring that the surrounding tissues are preserved while providing adequate exposure for the surgical procedure. This step is crucial for accessing the prostate or other pelvic organs and requires attention to avoid injury to the bladder and surrounding vasculature.",
    "Pedicles/NVB": "In the context of urology surgery, the teaching step \"Pedicles/NVB\" refers to the identification and preservation of the neurovascular bundles (NVB) and the associated pedicles during procedures such as prostatectomy. This step is crucial for maintaining erectile function and minimizing blood loss, requiring careful dissection and an understanding of the anatomical relationships in the pelvic region.",
    "Apical dissection": "Apical dissection involves carefully separating the tissue around the apex of the prostate to expose the neurovascular bundles while preserving critical structures. This step is crucial for ensuring adequate margins during prostatectomy and minimizing postoperative complications.",
    "DVC, hemostasis": "DVC (Dorsal Venous Complex) hemostasis involves identifying and controlling the dorsal venous complex during urological procedures, typically by clamping, ligating, or cauterizing the vessels to prevent excessive bleeding. This step is crucial for maintaining a clear surgical field and ensuring patient safety throughout the operation.",
    "Rocco": "The Rocco maneuver involves the careful dissection and preservation of the neurovascular bundles during radical prostatectomy to minimize postoperative erectile dysfunction. This step emphasizes the importance of identifying and sparing the cavernous nerves while ensuring adequate oncological control.",
    "Pexy": "Pexy refers to the surgical technique of anchoring or securing an organ or tissue to another structure, often used in procedures like bladder suspension to treat conditions such as urinary incontinence. In teaching this step, emphasize the importance of proper anatomical identification, tension management, and fixation techniques to ensure stability and prevent complications.",
    "Bowel mobilization + Lymph dissection": "Bowel mobilization involves carefully dissecting and freeing the bowel from surrounding structures to provide adequate access to the surgical site, while lymph dissection entails the systematic removal of lymph nodes in the region to assess for malignancy or to ensure complete tumor resection. Both steps are critical for minimizing complications and ensuring thorough surgical intervention in urological procedures.",
    "Endopelvic fascia ": "The endopelvic fascia is a connective tissue layer that supports pelvic organs and is crucial in urological surgeries. During teaching, emphasize the identification and preservation of this fascia to maintain pelvic organ support and prevent complications such as pelvic organ prolapse.",
    "Bladder neck / SV": "The bladder neck and seminal vesicle (SV) dissection involves carefully identifying and preserving the surrounding neurovascular structures while excising the tissue to access the bladder neck and seminal vesicles, ensuring minimal trauma to adjacent organs. This step is crucial for maintaining urinary function and sexual health post-surgery.",
    "pedicles / NVB": "In the surgical teaching step of managing pedicles and neurovascular bundles (NVB), emphasize the importance of careful dissection to preserve surrounding structures while ensuring adequate vascular supply to the surgical site. Instruct on identifying and protecting the NVB during procedures such as prostatectomy to minimize complications and optimize functional outcomes.",
    "apical dissection ": "Apical dissection involves carefully separating the tissue around the apex of the prostate to expose the neurovascular bundles while preserving critical structures. This step is crucial for minimizing postoperative complications and ensuring adequate oncological control during prostatectomy procedures.",
    "Hemostasis, DVC": "Hemostasis in the context of DVC (Dorsal Venous Complex) involves meticulously identifying and controlling bleeding vessels during the surgical procedure to prevent excessive blood loss. This is achieved through techniques such as clamping, cauterization, or ligation, ensuring a clear surgical field and promoting optimal healing.",
    "pexy": "Pexy refers to the surgical technique of anchoring or securing an organ or tissue to another structure, often used in procedures like cystopexy or nephropexy to stabilize the bladder or kidney, respectively. In teaching this step, emphasize the importance of proper anatomical identification, tension management, and the choice of suturing technique to ensure effective stabilization while minimizing complications.",
    "extra node dissection": "Extra node dissection involves the careful identification and removal of additional lymph nodes beyond the primary target to ensure comprehensive staging and treatment of malignancies, particularly in urological cancers. This step requires meticulous dissection techniques to minimize damage to surrounding structures while ensuring complete node retrieval for pathological evaluation.",
    "Bowel mobilization": "Bowel mobilization involves carefully dissecting and freeing the bowel from surrounding structures to create a clear surgical field, ensuring that the bowel can be safely retracted or manipulated without compromising its blood supply or function. This step is crucial for accessing the surgical site and minimizing the risk of postoperative complications.",
    "dissection": "Dissection involves carefully separating and isolating anatomical structures using surgical instruments, ensuring minimal trauma to surrounding tissues while providing clear access to the target area for further surgical intervention. This step requires a thorough understanding of anatomy and meticulous technique to avoid complications.",
    "dissecting ": "Dissecting involves carefully separating tissues and structures using surgical instruments to expose the target area while minimizing damage to surrounding tissues. This step is crucial for accessing the surgical site and ensuring a clear view for subsequent procedures.",
    "stapling ureter ": "The teaching step for stapling the ureter involves carefully aligning the ureteral edges to ensure proper tension and orientation, followed by the application of a surgical stapler to create a secure and watertight anastomosis. It is crucial to assess the integrity of the staple line and ensure there are no obstructions or kinks in the ureter post-stapling.",
    "Bagging specimen ": "Bagging the specimen involves carefully placing the excised tissue or organ into a sterile bag to prevent contamination and facilitate safe handling during transport to pathology. This step is crucial for maintaining specimen integrity and ensuring accurate diagnostic evaluation.",
    "undocking, specimen out, closing incisions": "Undocking involves carefully detaching the robotic surgical system from the patient after completing the procedure, ensuring all instruments are retracted safely. Specimen out refers to the meticulous removal of the excised tissue or organ, followed by closing incisions, which entails suturing or stapling the surgical openings to promote proper healing and minimize complications.",
    "docking robot": "Docking the robot involves positioning the robotic surgical system in alignment with the patient and securing the robotic arms to the surgical ports, ensuring optimal access and maneuverability for the procedure. This step is crucial for facilitating precise instrument control and maintaining a stable surgical field throughout the operation.",
    "(setting up, waiting for attending)": "In this teaching step, the surgical trainee prepares the operating room by ensuring all necessary instruments and supplies are sterile and organized, while also confirming the presence of the attending surgeon and any required team members before proceeding with the surgical procedure. This step emphasizes the importance of teamwork and communication in creating a safe and efficient surgical environment.",
    " Cystotomy": "Cystotomy is the surgical procedure involving an incision into the bladder to access its interior, typically performed to remove bladder stones, tumors, or to facilitate other surgical interventions. During teaching, emphasize the importance of proper incision technique, maintaining hemostasis, and ensuring bladder integrity to prevent complications.",
    "Stay Sutures": "Stay sutures are temporary sutures placed in strategic locations to provide traction and stability to tissues during surgery, facilitating better visualization and access to the surgical site. They are typically used to hold organs or structures in place, allowing the surgeon to work more efficiently and safely.",
    "Adenoma Dissection": "Adenoma dissection involves carefully identifying and separating the adenomatous tissue from surrounding structures using precise surgical techniques, ensuring minimal trauma to adjacent healthy tissue. This step is crucial for achieving complete resection while preserving functional anatomy and reducing the risk of complications.",
    "Bladder Neck ": "The bladder neck is the region where the bladder connects to the urethra, and during surgical teaching, it is essential to demonstrate the anatomy and function of the bladder neck, emphasizing its role in urinary continence and the techniques for preserving its integrity during procedures such as prostatectomy or bladder surgery. Instructors should guide trainees through identifying key structures, understanding potential complications, and practicing surgical maneuvers that minimize trauma to this area.",
    "Closing Bladder": "Closing the bladder involves carefully suturing the bladder wall using absorbable sutures in a continuous or interrupted fashion, ensuring proper alignment of the tissue layers to prevent leakage and promote healing. It is essential to maintain hemostasis and avoid tension on the sutures to minimize complications.",
    "Bowel Mobilization": "Bowel mobilization involves carefully dissecting and freeing the bowel from surrounding structures to create a clear surgical field and prevent injury to the intestines during urological procedures. This step is crucial for accessing the target organs and ensuring optimal visibility and maneuverability during surgery.",
    "Dissection": "Dissection involves carefully separating and isolating anatomical structures using surgical instruments, ensuring minimal trauma to surrounding tissues while providing clear visibility and access to the target area. This step is crucial for identifying critical structures and facilitating subsequent surgical maneuvers.",
    "bowel mobilization": "Bowel mobilization involves carefully dissecting and freeing the bowel from surrounding structures to create a clear surgical field, ensuring that the bowel can be safely retracted or manipulated without compromising its blood supply or function. This step is crucial for accessing the surgical site and minimizing the risk of postoperative complications.",
    "Dissection+VUA": "Dissection involves carefully separating tissues to access the surgical site while preserving surrounding structures, followed by VUA (Vesicourethral Anastomosis), which is the precise surgical connection of the bladder to the urethra to restore urinary continuity after procedures such as radical prostatectomy.",

In [34]:
teaching_steps_df['teaching_step_defn'] = teaching_steps_df['teaching_step'].map(teaching_step_mapppings)
teaching_steps_df.to_parquet('/home/firdavs/surgery/surgical_fb_generation/SurgicalFeedbackGeneration/data/urology-related/teaching_steps.parquet', index=False)

## Extract Embeddings

In [83]:
from sentence_transformers import SentenceTransformer

def get_medembed_embeddings(texts):
    medembed = SentenceTransformer('abhinand/MedEmbed-small-v0.1')
    embs = []
    for i in tqdm(range(len(texts)), desc='MedEmbed Embedding'):
        text = texts[i]
        emb = medembed.encode(text)
        embs.append(emb)
    return embs

In [74]:
from mmengine.config import Config
SurgVLP_path = '/home/firdavs/surgery/surgical_fb_generation/SurgVLP'
import sys
sys.path.append(SurgVLP_path)
import surgvlp

def get_vl_embs(model_name, texts, device='cuda'):    # model_name = 'surgvlp', 'peskavlp', 'hecvl'
    configs = Config.fromfile(os.path.join(SurgVLP_path, 'tests', 'config_peskavlp.py'), lazy_import=False)['config']
    model, _ = surgvlp.load(configs.model_config, device=device, strict_load_state_dict=False)
    text_embs = []
    for i in tqdm(range(len(texts)), desc=f'{model_name} Embedding'):
        text = surgvlp.tokenize([texts[i]], device=device)
        output_dict = model(None, text , mode='text')
        text_embs.append(output_dict['text_emb'][0].cpu().detach().numpy())
    return text_embs

### 1) Procedures

In [60]:
procedure_defn_embeddings = {
    'MedEmbed_small': [],
    'SurgVLP': [],
    'HecVL': [],
    'PeskaVLP': [],
}

In [ ]:
procedure_defn_embeddings['MedEmbed_small'] = get_medembed_embeddings(procedures_df['procedure_defn'].tolist())

MedEmbed Procedures Embedding: 100%|██████████| 35/35 [00:00<00:00, 251.69it/s]

In [62]:
procedure_defn_embeddings['SurgVLP'] = get_vl_embs('surgvlp', procedures_df['procedure_defn'].tolist())
procedure_defn_embeddings['HecVL'] = get_vl_embs('hecvl', procedures_df['procedure_defn'].tolist())
procedure_defn_embeddings['PeskaVLP'] = get_vl_embs('peskavlp', procedures_df['procedure_defn'].tolist())

surgvlp Embedding: 100%|██████████| 35/35 [00:29<00:00,  1.20it/s]
hecvl Embedding: 100%|██████████| 35/35 [00:20<00:00,  1.69it/s]
peskavlp Embedding: 100%|██████████| 35/35 [00:27<00:00,  1.27it/s]

In [68]:
for k, v in procedure_defn_embeddings.items():
    procedures_df[f'procedure_defn_emb-{k}'] = v

In [72]:
procedures_df.to_parquet('/home/firdavs/surgery/surgical_fb_generation/SurgicalFeedbackGeneration/data/urology-related/procedures.parquet', index=False)

### 2) Teaching Steps

In [76]:
teaching_step_defn_embeddings = {
    'MedEmbed_small': [],
    'SurgVLP': [],
    'HecVL': [],
    'PeskaVLP': [],
}

In [84]:
teaching_step_defn_embeddings['MedEmbed_small'] = get_medembed_embeddings(teaching_steps_df['teaching_step_defn'].tolist())

MedEmbed Embedding: 100%|██████████| 489/489 [00:01<00:00, 309.48it/s]

In [78]:
teaching_step_defn_embeddings['SurgVLP'] = get_vl_embs('surgvlp', teaching_steps_df['teaching_step_defn'].tolist())
teaching_step_defn_embeddings['HecVL'] = get_vl_embs('hecvl', teaching_steps_df['teaching_step_defn'].tolist())
teaching_step_defn_embeddings['PeskaVLP'] = get_vl_embs('peskavlp', teaching_steps_df['teaching_step_defn'].tolist())

/home/firdavs/miniconda3/envs/firdavs/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/firdavs/miniconda3/envs/firdavs/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
surgvlp Embedding: 100%|██████████| 489/489 [05:46<00:00,  1.41it/s]
hecvl Embedding: 100%|██████████| 489/489 [06:25<00:00,  1.27it/s]
peskavlp Embedding: 100%|██████████| 489/489 [06:47<00:00,  1.20it/s]

In [86]:
for k, v in teaching_step_defn_embeddings.items():
    teaching_steps_df[f'teaching_step_defn_emb-{k}'] = v

In [88]:
teaching_steps_df.to_parquet('/home/firdavs/surgery/surgical_fb_generation/SurgicalFeedbackGeneration/data/urology-related/teaching_steps.parquet', index=False)